# Generated by Django 5.0.7 on 2024-08-27 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_department_position_alter_employee_department_and_more'),
        ('dashboard', '0006_remove_employee_gender_user_gender'),
    ]

    operations = [
    ]
