# Generated by Django 5.0.7 on 2024-08-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_merge_20240827_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='gender_restriction',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'any')], default='any', max_length=10),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
